baseURL = "https://notjulian.github.io/blog/"
languageCode = "en-us"
title = "JC Software Blog"
theme = "hugo-theme-m10c"

[params]
  author = "JC"
  description = "A blog about."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/notjulian"

  [[params.social]]
    icon = "twitter"
    name = "X"
    url = "https://x.com/_notjulian"
