baseURL = "https://notjulian.github.io/blog/"
languageCode = "en-us"
title = "JC Software Blog"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[pagination]
  pagerSize = 8

[params]
  mode="auto"
  useCDN=false
  author = "JC"
  description = "A blog about stuff."

[[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/notjulian"

[[params.social]]
    icon = "x"
    name = "X"
    url = "https://x.com/_notjulian"
